name: deploy node application

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t mdshayemur01/resumeGen-backend .
      - name: Publish Image to docker hub
        run: docker push mdshayemur01/resumeGen-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull mdshayemur01/resumeGen-backend:latest
      - name: Delete Old Container
        run: docker rm -f resumeGen-backend-container
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name resumeGen-backend-container -e DB_URL='${{ secrets.DB_URL }}' -e TOKEN_SECRET='${{ secrets.TOKEN_SECRET }}' mdshayemur01/resumeGen-backend:latest